# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase
from mubulogin_test import TestCaseMubuLogin as MubuLogin


class TestCaseMubu(HttpRunner):
    config = (
        Config("testcase description")
        .variables(
            **{
                "memberId": "433746469027333",
                "host": "mubu.com",
                "phone": "18668091423",
                "password": "85119850",
            }
        )
        .base_url("https://$host/")
        .verify(False)
    )

    teststeps = [
        Step(RunTestCase("login").call(MubuLogin)),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.$host/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ee6ac542-181b-43f9-be6f-5db6e31dcf1c",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/activity/five_years/participation")
            .post("https://api2.$host/v3/api/activity/five_years/participation")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "a2fac45a-ebc7-40da-9d42-17a89559ef79",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 4011)
            .assert_equal("body.msg", "unknown error")
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.$host/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "13b32298-e2f5-4c6e-afa8-4097e2bd38db",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.$host/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "b662aaf9-8ae3-4936-b490-2b930dc333ad",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.$host/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "e98ff469-3c2d-4e70-881a-a3b60987363e",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/get_onboard_state")
            .post("https://api2.$host/v3/api/user/get_onboard_state")
            .with_headers(
                **{
                    "content-length": "2",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ecc6b6ba-6974-40c7-9bd1-7243cc88020b",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.$host/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "d6789998-6908-4421-b55a-bc7754ff26e7",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.$host/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "95056172-f7d4-4379-9a7f-66022a7a5a83",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.$host/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "88abcd3c-2bae-4605-86e6-28057ed467d4",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .teardown_hook("${get_folders_num($response)}", "folders_num")
            .validate()
            .assert_equal("status_code", 200)
            .assert_greater_or_equals("$folders_num", 0)
        ),
        Step(
            RunRequest("/v3/api/notify/new_tip/get")
            .post("https://api2.$host/v3/api/notify/new_tip/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ce4b60ef-b31b-4d90-b0f2-194567319b6c",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.$host/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://$host",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.$host/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "52252900-8d33-43f0-9edc-94e7fad13696",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id", "docID")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.$host/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "7a475f3f-2b40-4b84-84b0-df485b919f0e",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.$host/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "760383cb-de1a-4673-98d8-67d95f900932",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"docId": "${docID}", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.$host/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ee3761a5-9b9d-48f0-bece-e2141de7155d",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "93",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "b4d5ae31-2367-47fb-a268-92af03cf2bbe",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "reqId": "1",
                    "type": "USER_HEARTBEAT",
                    "memberId": "${memberId}",
                    "documentId": "${docID}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.$host/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "4a23146c-b410-4ef3-880c-2663fe4be92a",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"targetDocId": "${docID}"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("https://api2.$host/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "0b5808be-2742-4c8e-b23f-68dfe1a7234e",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"targetDocId": "${docID}"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members_v2")
            .post("https://api2.$host/v3/api/colla/members_v2")
            .with_headers(
                **{
                    "content-length": "57",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "request-id": "members:${memberId}:1624693357557",
                    "x-request-id": "233d1d0d-e144-413c-8324-abaeb76f911f",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"memberId": "${memberId}", "documentId": "${docID}"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "205",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ab618070-155d-4fe6-a9b5-ffd088aa45f3",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "reqId": "2",
                    "memberId": "${memberId}",
                    "type": "CURSOR",
                    "documentId": "${docID}",
                    "cursor": {
                        "anchorId": "",
                        "anchorOffset": 0,
                        "anchorNodeType": "title",
                        "focusId": "",
                        "focusOffset": 0,
                        "focusNodeType": "title",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "205",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "f34a8e3c-549d-4454-91f6-8c29828b2285",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "reqId": "3",
                    "memberId": "${memberId}",
                    "type": "CURSOR",
                    "documentId": "${docID}",
                    "cursor": {
                        "anchorId": "",
                        "anchorOffset": 2,
                        "anchorNodeType": "title",
                        "focusId": "",
                        "focusOffset": 2,
                        "focusNodeType": "title",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "196",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "0f7eb252-d0d1-401e-b16c-d111936b781d",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 0,
                    "documentId": "${docID}",
                    "events": [
                        {"name": "nameChanged", "title": "d", "original": ""},
                        {"name": "nameChanged", "title": "de", "original": "d"},
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "204",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "55a29960-e224-46cf-a4cd-2fd9a450613c",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 1,
                    "documentId": "${docID}",
                    "events": [
                        {"name": "nameChanged", "title": "dem", "original": "de"},
                        {"name": "nameChanged", "title": "demo", "original": "dem"},
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "205",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "2a8ed320-f49a-46e9-9e34-8818299e7c4b",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "reqId": "4",
                    "memberId": "${memberId}",
                    "type": "CURSOR",
                    "documentId": "${docID}",
                    "cursor": {
                        "anchorId": "",
                        "anchorOffset": 4,
                        "anchorNodeType": "title",
                        "focusId": "",
                        "focusOffset": 4,
                        "focusNodeType": "title",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.$host/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "52",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "45193dd6-c02e-495f-9670-f97f77ccf11f",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"docId": "${docID}", "keywords": "demo", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "249",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "d2c47052-eaf3-48f8-955e-c1db3b0f8211",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 2,
                    "documentId": "${docID}",
                    "events": [
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 0,
                                    "parentId": None,
                                    "node": {
                                        "id": "IrsukPa0J1",
                                        "text": "",
                                        "modified": 1624693360934,
                                        "children": [],
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "294",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "87ded37b-4e1b-4777-bb90-8e3160bfb534",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 3,
                    "documentId": "${docID}",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "IrsukPa0J1",
                                        "text": "<span>111</span>",
                                        "modified": 1624693362386,
                                    },
                                    "original": {
                                        "id": "IrsukPa0J1",
                                        "text": "",
                                        "modified": 1624693360934,
                                    },
                                    "path": ["nodes", 0],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "249",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "4c3764a9-ca7b-4674-9547-0736b8cdff4e",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 4,
                    "documentId": "${docID}",
                    "events": [
                        {
                            "name": "create",
                            "created": [
                                {
                                    "index": 1,
                                    "parentId": None,
                                    "node": {
                                        "id": "CjOctECkjS",
                                        "text": "",
                                        "modified": 1624693363184,
                                        "children": [],
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "294",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "4e5272ea-68e5-4b55-98cd-ca25ab8ba87d",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "memberId": "${memberId}",
                    "type": "CHANGE",
                    "version": 5,
                    "documentId": "${docID}",
                    "events": [
                        {
                            "name": "update",
                            "updated": [
                                {
                                    "updated": {
                                        "id": "CjOctECkjS",
                                        "text": "<span>222</span>",
                                        "modified": 1624693363688,
                                    },
                                    "original": {
                                        "id": "CjOctECkjS",
                                        "text": "",
                                        "modified": 1624693363184,
                                    },
                                    "path": ["nodes", 1],
                                }
                            ],
                        }
                    ],
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/events")
            .post("https://api2.$host/v3/api/colla/events")
            .with_headers(
                **{
                    "content-length": "87",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "f24cef30-f5d0-469e-8e58-ef2865e8e103",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "reqId": "11",
                    "type": "UNWATCH",
                    "memberId": "${memberId}",
                    "documentId": "${docID}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/notify/new_tip/get")
            .post("https://api2.$host/v3/api/notify/new_tip/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "6e74105a-34ac-4c5f-b42e-719942d7a414",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.$host/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "a231690f-43c3-4363-b9bf-576353a938af",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
