# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubuLogin(HttpRunner):
    config = (
        Config("testcase description")
        .variables(
            **{
                "memberId": "433746469027333",
                "host": "mubu.com",
                "phone": "18668091423",
                "password": "85119850",
            }
        )
        .base_url("https://$host/")
        .verify(False)
    )

    teststeps = [
        Step(
            RunRequest("/")
            .get("/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "dnt": "1",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "none",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1624608288",
                    "_ga": "GA1.2.482573863.1624608288",
                    "_gid": "GA1.2.528458330.1624608288",
                    "reg_entrance": "https%3A%2F%2F$host%2F",
                    "csrf_token": "859e6765-fa77-43ad-8f4c-ab7518b66435",
                    "language": "en-US",
                    "country": "US",
                    "SESSION": "6ee26b31-e282-4559-a8ab-f4a0a97b8d80",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "48abf4af-c71c-4fd0-80a1-5bd8dc996099",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1624693331",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "dnt": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1624608288",
                    "_ga": "GA1.2.482573863.1624608288",
                    "_gid": "GA1.2.528458330.1624608288",
                    "reg_entrance": "https%3A%2F%2F$host%2F",
                    "csrf_token": "859e6765-fa77-43ad-8f4c-ab7518b66435",
                    "language": "en-US",
                    "country": "US",
                    "SESSION": "6ee26b31-e282-4559-a8ab-f4a0a97b8d80",
                    "_gat": "1",
                    "SLARDAR_WEB_ID": "e2674511-a915-45ad-9b37-40687d4b3b09",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1624693338",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.$host/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "f9f1068a-8d45-41d0-babf-ae9c3f5fe1ac",
                    "version": "3.0.0-2.0.0.1717",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/phone_login")
            .with_variables(**{"callbackType": 0, "timestamp": "get_timestamp()"})
            .post("https://api2.$host/v3/api/user/phone_login")
            .with_headers(
                **{
                    "content-length": "62",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "",
                    "x-request-id": "4fab103b-8284-4a66-860a-f0fc7448037b",
                    "version": "3.0.0-2.0.0.1717",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_json(
                {
                    "phone": "$phone",
                    "password": "$password",
                    "callbackType": "$callbackType",
                    "token": "${get_token($phone,$password,$timestamp)}",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/app")
            .get("/app")
            .with_headers(
                **{
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "dnt": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://$host/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1624608288",
                    "_ga": "GA1.2.482573863.1624608288",
                    "_gid": "GA1.2.528458330.1624608288",
                    "reg_entrance": "https%3A%2F%2F$host%2F",
                    "csrf_token": "859e6765-fa77-43ad-8f4c-ab7518b66435",
                    "language": "en-US",
                    "country": "US",
                    "SESSION": "6ee26b31-e282-4559-a8ab-f4a0a97b8d80",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1624693340",
                    "SLARDAR_WEB_ID": "0a8f8eaf-4c4c-4cc2-a365-9e04db4925f4",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.$host/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
                    "dnt": "1",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36",
                    "data-unique-id": "f16e779a-6b64-43d7-98c9-33a79b07a8d8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTI0ODM3NTAiLCJsb2dpblR5cGUiOiJtb2JpbGUiLCJleHAiOjE2MjcyODUzNTAsImlhdCI6MTYyNDY5MzM1MH0.nkSri2w5s6LEyt7LQUy7_1IQEF92OWq4jpg_cjgkMUPEewkAFPIfAsU6sCxUWXWjbC-P2TRfU421cxC1Gj1ycw",
                    "x-request-id": "ee6ac542-181b-43f9-be6f-5db6e31dcf1c",
                    "version": "3.0.0-2.0.0.1716",
                    "origin": "https://$host",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://$host/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9,en;q=0.8",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuLogin().test_start()
